---
name: Encode-ZapCP1252
version: 0.10
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Zap Windows Western Gremlins
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  perl: 5.6.2
build_requires:
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Encode::ZapCP1252:
    file: lib/Encode/ZapCP1252.pm
    version: 0.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
