---
abstract: 'Zap Windows Western Gremlins'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.36
  Test::More: 0.17
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-ZapCP1252
provides:
  Encode::ZapCP1252:
    file: lib/Encode/ZapCP1252.pm
    version: 0.33
recommends:
  Encode: 0
  Test::Pod: 1.41
requires:
  perl: 5.006002
resources:
  bugtracker: http://github.com/theory/encode-cp1252/issues/
  homepage: http://search.cpan.org/dist/Encode-CP1252/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/encode-cp1252/tree
version: 0.33
